{#
    Union different combinations of columns from multiple existing tables (or CTEs) together.
    tables_dict is a dictionary of references for keys
    and values comprised of a tuple for the source tables
    key date field and list of fields to union.
    See ent_quotes for an example input.

    tables_dict = {table_ref, (datetime_field, [field1, field2])}
        If the value for the field array is '*' this will return all fields. Ie ['*'].
    lst_type = 'include' / 'exclude' determines whether the list of fields provided will be included or held out.
    final_cte_str = 'union_cte' by default, what to name the output cte of this macro.
    is_materialized_incremental = true by default, whether the model using the macros is materialized incrementally.
        This controls the inclusion of a where clause to limit ingestion by the datetime_field.
#}

{% macro union_select_columns(tables_dict, lst_type='include', final_cte_str='union_cte', is_materialized_incremental=false) -%}

-- Begin code generated by macro union_select_columns.
-- Create a unified list of all columns across the chosen tables
{% set columns_lst = [] -%}
{% set table_cols_dict = {} -%}
{%- for table in tables_dict.keys() -%}
    {%- set table_cols_lst = [] -%}
    {%- if ('*' in tables_dict.get(table)[1] and '.' in table|string) or lst_type != 'include' -%}
        {%- set adapter_cols = adapter.get_columns_in_relation(table) -%}
        {%- if lst_type != 'include' -%}
            {%- for col in adapter_cols -%}
                {%- if col.column|string|lower not in tables_dict.get(table)[1] -%}
                    {%- do columns_lst.append(col.column|string|lower) -%}
                    {%- do table_cols_lst.append(col.column|string|lower) -%}
                {%- endif -%}
            {%- endfor -%}
        {%- else -%}
            {%- for col in adapter_cols -%}
                {%- do columns_lst.append(col.column|string|lower) -%}
                {%- do table_cols_lst.append(col.column|string|lower) -%}
            {%- endfor -%}
        {%- endif -%}
    {%- else -%}
        {%- do columns_lst.extend(tables_dict.get(table)[1]) -%}
        {%- set table_cols_lst = tables_dict.get(table)[1] -%}
    {%- endif -%}
    {%- do table_cols_dict.update({table: table_cols_lst}) -%}
{%- endfor -%}
{%- set columns_lst = columns_lst|unique|sort -%}

-- Loop through every table to be union'd and create a CTE for it.
{% for table in tables_dict.keys() -%}
    {%- set cte_name = table|string -%}
    {%- set cte_name = cte_name.split('.')[-1] %}
    {%- set table_cols_lst = table_cols_dict.get(table) -%}
    {{ cte_name }}_cte as (
        select
            -- If the column exists in the target table simply add it to the select list.
            -- If the column does not exist in the target table set it to null for this CTE.
            {% for col in columns_lst -%}
                {%- if col in table_cols_lst -%}
                {{ col }}{%- if not loop.last -%},{% endif %}
                {%- else -%}
                null as {{ col }}{%- if not loop.last -%},{% endif %}
                {%- endif %}
            {% endfor -%}
        from {{ table }}
        {% if is_materialized_incremental and is_incremental() -%}
        where {{ tables_dict.get(table)[0] }} > (select(max(dateadd(day, -7, {{ tables_dict.get(table)[0] }}))) from {{ table }})
        {%- endif -%}
        
    ),
{% endfor -%}

-- Perform a union all to join all the CTEs created by the above loop.
{{ final_cte_str }} as (
    {%- for table in tables_dict.keys() %}
    {%- set cte_name = table|string -%}
    {%- set cte_name = cte_name.split('.')[-1] %}

    select *
    from {{ cte_name }}_cte
    {% if not loop.last %}union all{% endif -%}
    {% endfor %}
)
-- End code generated by macro union_select_columns.
{% endmacro%}
