{%- macro dynamic_source_selection(
    table_alias=None,
    target_source=None,
    source_time_field=None,
    target_time_field=None
)
-%}
/* Begin dynamic_source_selection macro. */
{%- set target_source_str = target_source|string -%}
{%- set target_lst = target_source_str.split('.') -%}

{%- if 'test' in target.database.lower() -%}
from dbt_test.dbt_seeds.seed__{{ target_lst[1] }}__{{target_lst[2] }}
{%- else -%}
from {{ target_source }}
{%- endif %}

{% if 'local_' in target.database.lower() -%}
    where {{ table_alias ~ '.' if table_alias }}{{ source_time_field }} > '{{ var("LOCAL_CUTOFF_DATE")  }}'
{% elif 'test' in target.database.lower() and is_incremental() -%}
    where {{ source_time_field }} > (select max(dateadd(day, -7, date_trunc(day, {{ table_alias ~ '.' if table_alias }}{{ source_time_field }}))) from dbt_test.dbt_seeds.seed__{{ target_lst[1] }}__{{target_lst[2] }})
{% elif is_incremental() -%}
    where {{ source_time_field }} > (select max(dateadd(day, -7, date_trunc(day, {{ table_alias ~ '.' if table_alias }}{{ source_time_field }}))) from {{ target_source }})
{%- endif -%}
/* End code generated by dynamic_source_selection macro. */
{%- endmacro -%}
