{%- macro dynamic_warehouse_selection() -%}
/* Begin dynamic_warehouse_selection macro. */
{%- set warehouse_dict = generate_warehouse_sizes() -%}


{%- if target.name == 'test' -%}
    {%- set snowflake_warehouse = 'XS_WH' -%}
{%- elif flags.FULL_REFRESH == True -%}
    {%- set snowflake_warehouse = warehouse_dict.get(model.name)[0] -%}
{%- else -%}
    {%- set snowflake_warehouse = warehouse_dict.get(model.name)[1] -%}
{%- endif -%}


{%- if snowflake_warehouse == Null -%}
    {%- set snowflake_warehouse = 'XS_WH' -%}
{%- endif -%}

{{ return(snowflake_warehouse) }}
/* End code generated by dynamic_warehouse_selection macro. */
{%- endmacro -%}

